/**
 * Location data for Bangladesh - Division, City, and Area mappings
 */

export const LOCATION_DATA = {
  "Dhaka Division": {
    "Dhaka": [
      "Uttara",
      "Mirpur",
      "Mohammadpur",
      "Adabor",
      "Dhanmondi",
      "Tejgaon",
      "Gulshan",
      "Banani",
      "Badda",
      "Rampura",
      "Khilgaon",
      "Jatrabari",
      "Lalbagh",
      "Kotwali",
      "Sutrapur"
    ],
    "Gazipur": [
      "Gazipur Sadar",
      "Tongi",
      "Kaliakair",
      "Kaliganj",
      "Sreepur",
      "Board Bazar",
      "Pubail",
      "Konabari",
      "Kapasia",
      "Bason",
      "Joydebpur",
      "Mirzapur",
      "Mawna",
      "Cherag Ali",
      "Salna"
    ],
    "Narayanganj": [
      "Narayanganj Sadar",
      "Fatullah",
      "Bandar",
      "Araihazar",
      "Rupganj",
      "Sonargaon",
      "Siddhirganj",
      "Kanchpur",
      "Gognagar",
      "Langolbond",
      "Bhulta",
      "Pagla",
      "Aliganj",
      "Adamjee",
      "Madanpur"
    ],
    "Narsingdi": [
      "Narsingdi Sadar",
      "Palash",
      "Raipura",
      "Shibpur",
      "Belabo",
      "Monohardi",
      "Ghorashal",
      "Madhabdi",
      "Chandpara",
      "Hatirdia",
      "Bashail",
      "Danga",
      "Karimpur",
      "Panchdona",
      "Amlaba"
    ],
    "Munshiganj": [
      "Munshiganj Sadar",
      "Sreenagar",
      "Sirajdikhan",
      "Lohajang",
      "Tongibari",
      "Gazaria",
      "Baligaon",
      "Hashara",
      "Mirkadim",
      "Rampal",
      "Betka",
      "Ichhapura",
      "Bajrajogini",
      "Modonpur",
      "Kathakhali"
    ],
    "Manikganj": [
      "Manikganj Sadar",
      "Saturia",
      "Singair",
      "Ghior",
      "Shibalaya",
      "Daulatpur",
      "Harirampur",
      "Baliakhora",
      "Terokhada",
      "Betila",
      "Joymontop",
      "Azimpur",
      "Baira",
      "Kanchanpur",
      "Lechraganj"
    ],
    "Tangail": [
      "Tangail Sadar",
      "Kalihati",
      "Ghatail",
      "Madhupur",
      "Mirzapur",
      "Nagarpur",
      "Gopalpur",
      "Basail",
      "Delduar",
      "Sakhipur",
      "Dhanbari",
      "Bhuapur",
      "Jamuna Bridge East",
      "Charabari",
      "Atia"
    ],
    "Kishoreganj": [
      "Kishoreganj Sadar",
      "Bhairab",
      "Katiadi",
      "Karimganj",
      "Tarail",
      "Pakundia",
      "Kuliarchar",
      "Hossainpur",
      "Itna",
      "Mithamain",
      "Austagram",
      "Bajitpur",
      "Nikli",
      "Chandpur",
      "Latibabad"
    ],
    "Faridpur": [
      "Faridpur Sadar",
      "Boalmari",
      "Madhukhali",
      "Bhanga",
      "Nagarkanda",
      "Sadarpur",
      "Charbhadrasan",
      "Alfadanga",
      "Saltha",
      "Kanaipur",
      "Gerda",
      "Ambikapur",
      "Baitul Aman",
      "Decreerchar",
      "Krishnanagar"
    ],
    "Gopalganj": [
      "Gopalganj Sadar",
      "Kashiani",
      "Kotalipara",
      "Tungipara",
      "Muksudpur",
      "Raghunathpur",
      "Ulpur",
      "Sajail",
      "Patgati",
      "Nijra",
      "Batikamari",
      "Gobindapur",
      "Haridaspur",
      "Barni",
      "Chandradighalia"
    ],
    "Madaripur": [
      "Madaripur Sadar",
      "Rajoir",
      "Kalkini",
      "Shibchar",
      "Mustafapur",
      "Charmuguria",
      "Panchkhola",
      "Bahadurpur",
      "Khoyajpur",
      "Khoajpur",
      "Kadirpur",
      "Umedpur",
      "Dudhkhali",
      "Baligram",
      "Ghatmajhi"
    ],
    "Rajbari": [
      "Rajbari Sadar",
      "Goalanda",
      "Pangsha",
      "Baliakandi",
      "Kalukhali",
      "Daulatdia",
      "Majhbari",
      "Ratandia",
      "Baharpur",
      "Islampur",
      "Sajjankanda",
      "Mrigi",
      "Narua",
      "Shahid Wahabpur",
      "Chandani"
    ],
    "Shariatpur": [
      "Shariatpur Sadar",
      "Naria",
      "Zajira",
      "Bhedarganj",
      "Gosairhat",
      "Damudya",
      "Palong",
      "Angaria",
      "Tulasar",
      "Chikandi",
      "Kartickpur",
      "Rudrakar",
      "Chandrapur",
      "Mahmudpur",
      "Jajira"
    ]
  }
};

